before_commands:
    - "composer install --prefer-dist"

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_sim: true
    php_changetracking: true
    sensiolabs_security_checker: true
    php_mess_detector: true
    php_code_sniffer: true
    php_analyzer: true
    php_code_coverage: false
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor/*]
filter:
    excluded_paths: [vendor/*]
