language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

env:
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=3.0.*@dev

before_script:
    - composer require symfony/yaml:${SYMFONY_VERSION} --no-update
    - composer require symfony/class-loader:${SYMFONY_VERSION} --no-update
    - composer update

script:
    - vendor/bin/behat
