language: php

php:
    - 5.5.9
    - 5.6
    - 7.0
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly

env:
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*

before_script:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer update

script:
    - vendor/bin/behat --config Tests/behat-jwt.yml
    - vendor/bin/behat --config Tests/behat-simple-string.yml
