language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

env:
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=3.0.*@dev

before_script:
    - composer require symfony/yaml:${SYMFONY_VERSION} --no-update
    - composer require symfony/class-loader:${SYMFONY_VERSION} --no-update
    - composer require symfony/symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/symfony/security-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/symfony/finder:${SYMFONY_VERSION} --no-update
    - composer require symfony/symfony/form:${SYMFONY_VERSION} --no-update
    - composer require symfony/symfony/twig-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/symfony/validator:${SYMFONY_VERSION} --no-update
    - composer require symfony/symfony/event-dispatcher:${SYMFONY_VERSION} --no-update
    - composer require symfony/symfony/yaml:${SYMFONY_VERSION} --no-update
    - composer require symfony/symfony/var-dumper:${SYMFONY_VERSION} --no-update
    - composer update

script:
    - vendor/bin/behat
