<?php

namespace SpomkyLabs\OAuth2ServerBundle\Plugin\ResourceOwnerPasswordCredentialsGrantTypePlugin\Grant;

use OAuth2\Configuration\ConfigurationInterface;
use OAuth2\EndUser\EndUserManagerInterface;
use OAuth2\Exception\ExceptionManagerInterface;
use OAuth2\Grant\ResourceOwnerPasswordCredentialsGrantType as BaseResourceOwnerPasswordCredentialsGrantType;

class ResourceOwnerPasswordCredentialsGrantType extends BaseResourceOwnerPasswordCredentialsGrantType
{
}
